### ISSUE TITLE
Modificar encendido :P

### ISSUE THREAD

**Issue by FDSoftware** [FDSoftware/OpenEFI#3]
Modifica el control de encendido para que use la tabla, usa las mismas funciones que uso yo para el de inyección, no reinventes la rueda al pedo xDD

**Comment by FrancisJPK** [comment]
parcialmente resuelto

**Comment by FDSoftware** [comment]
> Parcialmente arreglado en alpha2

[https://github.com/FDSoftware/OpenEFI/releases/tag/v0.2.0-alpha](url)
